# Introduction


**What?** Tensor operations



# Import modules
<hr style="border:2px solid black"> </hr>

In [ ]:
from numpy import array

# Tensor
<hr style="border:2px solid black"> </hr>


- Let's defines  `3x3x3` tensor as a `NumPy ndarray`.



In [1]:
# create tensor

T = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


# Tensor addition
<hr style="border:2px solid black"> </hr>


- This is an **element-wise** operation
- This means elemntt (i,i) of matrix No. 1 get summed with element (i,i) of matrix No. 2
- By extension we also have that element (i,i,i) of matrix No. 1 get summed with element (i,i,i) of matrix No. 2



In [6]:
from numpy import array
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


# Tensor subtraction
<hr style="border:2px solid black"> </hr>


- This is an **element-wise** operation
- This means elemntt (i,i) of matrix No. 1 get subtracted with element (i,i) of matrix No. 2
- By extension we also have that element (i,i,i) of matrix No. 1 get subtracted with element (i,i,i) of matrix No. 2



In [3]:
from numpy import array
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


# Tensor Hadamard product
<hr style="border:2px solid black"> </hr>


- This is an **element-wise** operation
- This means elemntt (i,i) of matrix No. 1 get multiplied with element (i,i) of matrix No. 2
- By extension we also have that element (i,i,i) of matrix No. 1 get multiplied with element (i,i,i) of matrix No. 2



In [ ]:
from numpy import array
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A * B
print(C)

# Tensor division
<hr style="border:2px solid black"> </hr>


- This is an **element-wise** operation
- This means elemntt (i,i) of matrix No. 1 get multiplied with element (i,i) of matrix No. 2
- By extension we also have that element (i,i,i) of matrix No. 1 get multiplied with element (i,i,i) of matrix No. 2



In [5]:
from numpy import array
A = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
